### ISSUE TITLE
pagination: not clear how its done

### ISSUE THREAD

**Issue by sckott** [figshare/user_documentation#39]
In the responses to at least the search endpoint, and maybe others, it's not clear how the client knows how to proceed. That is, with some pseudocode e.g., 

```
curl "https://api.figshare.com/v2/articles/search" -d '{
    "search_for": "Boettiger",
    "limit": 10,
    "offset": 0
}'
```

the response AFAICT has no information in body or headers on how many objects are remaining. Am I missing something, or is this bit not added yet?

**Comment by tachirei** [comment]
Hi @sckott,

Yes, you're right: there is no information on how many items are remaining.
At this moment, for a given query, the maximum number of listing/searching results is limited to **1000**.
You can further refine these results by using a filter such as `published_since`.
You can also change the order of the results by using the `order` and `order_direction` params:

```
curl "https://api.figshare.com/v2/articles/search" -d '{
  "search_for": "Boettiger",
  "limit": 10,
  "offset": 0,
  "published_since": "2000-01-02T03:04:05Z",
  "order": "published_date",
  "order_direction": "asc"
}'
```

For getting the next page, an API client should perform the same query, but with the `offset` value incremented by the number of results on the current page. When the number of results is less than the `limit`, there are no more results/pages.

Also, instead of the `offset` and `limit` params, you can use `page` and `page_size`.

```
curl "https://api.figshare.com/v2/articles/search" -d '{
  "search_for": "Boettiger",
  "page_size": 10,
  "page": 1,
  "published_since": "2000-01-02T03:04:05Z",
  "order": "published_date",
  "order_direction": "asc"
}'
```

If you want to read **ALL** the results, you can try the following:

1. issue one search request with `offset:0` and `limit:1000`, ordering by `published_date` *asc*ending to obtain the first 1000 results
2. from these results, get the greatest value of the  `published_date`
3. issue another search request with `offset:0`, `limit:1000`, `order:'published_date'`, `order_direction:"asc"` and `published_since: the_datetime_obtained_at_step_2`
4. repeat steps 2 and 3 until a response contains less items than the limit

**Comment by sckott** [comment]
thanks - any plans to include information on pagination in results/response headers ?

**Comment by tachirei** [comment]
I'm afraid that there are no plans to include pagination information in the response. Please make a [feature request](https://support.figshare.com/support/discussions/forums/6000240572/recent) and we'll schedule it for development.

**Comment by sckott** [comment]
Interesting. Then how does the Figshare.com deal with paging?  I guess you do a continuous scroll so you don't need to worry about how many results are remaining. knowing how many items remain seems like a fundamental feature of pagination for progammatic clients at least. 

Seems like no feature requests have been implemented though https://support.figshare.com/support/discussions/forums/6000240572/implemented

**Comment by elnordico** [comment]
Hi Scott, 

Product manager here. We've not really promoted our end user feature requests section yet, it's very new and we're mainly dealing with feature requests from our institutional clients. 

Our API team runs as a separate stream and is able to accommodate validated feature requests quite quickly. If you make a feature request on the board, you can always email me on chris @ figshare.com for a dialogue. 

Chris

**Comment by sckott** [comment]
Thanks @elnordico
